import React, { useState } from 'react';
import { User, ActiveView, ActivityLog } from '../../types';
import { DbStatusInfo } from '../../services/api';
import { ChangePasswordModal } from '../auth/ChangePasswordModal';

interface TopNavBarProps {
  currentUser: User | null;
  activeView: ActiveView;
  setActiveView: (view: ActiveView) => void;
  onLogout: () => void;
  availableUsers: User[];
  onSwitchUser: (user: User) => void;
  recentLogs: ActivityLog[];
  dbStatus?: DbStatusInfo | null;
  onReconnectDb?: () => void;
  onToast?: (type: 'success' | 'error' | 'info' | 'warning', title: string, message: string) => void;
}

export const TopNavBar: React.FC<TopNavBarProps> = ({
  currentUser,
  activeView,
  setActiveView,
  onLogout,
  availableUsers,
  onSwitchUser,
  recentLogs,
  dbStatus,
  onReconnectDb,
  onToast
}) => {
  const [showNotifications, setShowNotifications] = useState(false);
  const [showUserMenu, setShowUserMenu] = useState(false);
  const [showDbModal, setShowDbModal] = useState(false);
  const [showChangePasswordModal, setShowChangePasswordModal] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [isReconnecting, setIsReconnecting] = useState(false);
  const [copiedSql, setCopiedSql] = useState(false);


  const handleCopySql = () => {
    const sqlText = `-- ============================================================================
-- DynaPro - Esquema Completo, Permisos e Inserts Iniciales para Supabase
-- Centro Latinoamericano de Especies Menores (SENA CLEM - Tuluá)
-- ============================================================================

CREATE TABLE IF NOT EXISTS departments (id BIGINT PRIMARY KEY, name TEXT NOT NULL, code TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS cities (id BIGINT PRIMARY KEY, department_id BIGINT NOT NULL, name TEXT NOT NULL, code TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS training_centers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, city_id BIGINT);
CREATE TABLE IF NOT EXISTS training_groups (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, number TEXT NOT NULL UNIQUE, training_program TEXT NOT NULL, schedule TEXT NOT NULL DEFAULT 'Diurna', status TEXT NOT NULL DEFAULT 'Activo', training_center_id BIGINT DEFAULT 1, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_type TEXT NOT NULL DEFAULT 'CC', document TEXT NOT NULL UNIQUE, full_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, phone TEXT, role TEXT NOT NULL DEFAULT 'INSTRUCTOR', status TEXT NOT NULL DEFAULT 'Activo', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS projects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, training_center_id BIGINT DEFAULT 1, training_center_name TEXT NOT NULL, regional_name TEXT NOT NULL, beneficiaries TEXT, executive_summary TEXT, keywords JSONB DEFAULT '[]'::jsonb, general_objective TEXT, specific_objectives JSONB DEFAULT '[]'::jsonb, start_date DATE NOT NULL, end_date DATE NOT NULL, total_budget NUMERIC(15, 2) DEFAULT 0.00, status TEXT NOT NULL DEFAULT 'EN EJECUCIÓN', progress INT DEFAULT 0, created_by_user_id BIGINT, is_deleted BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS project_authors (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL, user_id BIGINT NOT NULL, is_principal BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS project_training_groups (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL, training_group_id BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS project_attachments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL, file_name TEXT NOT NULL, file_size BIGINT NOT NULL, file_type TEXT NOT NULL, data_url TEXT, uploaded_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS activity_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, user_name TEXT NOT NULL, user_avatar TEXT, action_label TEXT NOT NULL, action_type TEXT NOT NULL, detail TEXT NOT NULL, module TEXT NOT NULL, payload JSONB, timestamp TIMESTAMPTZ DEFAULT NOW());

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- INSERTS INICIALES
INSERT INTO departments (id, name, code) VALUES
(1, 'Valle del Cauca', '76'), (2, 'Antioquia', '05'), (3, 'Distrito Capital', '11'), (4, 'Caldas', '17'), (5, 'Santander', '68')
ON CONFLICT (id) DO NOTHING;

INSERT INTO cities (id, department_id, name, code) VALUES
(1, 1, 'Guadalajara de Buga', '76111'), (2, 1, 'Cali', '76001'), (3, 1, 'Palmira', '76520'), (4, 1, 'Tuluá', '76834'), (5, 2, 'Medellín', '05001'), (6, 2, 'Rionegro', '05615'), (7, 3, 'Bogotá D.C.', '11001'), (8, 4, 'Manizales', '17001'), (9, 5, 'Bucaramanga', '68001')
ON CONFLICT (id) DO NOTHING;

INSERT INTO training_centers (id, code, name, city_id, regional_name) VALUES
(1, 'CLEM-9201', 'CLEM - Centro Latinoamericano de Especies Menores', 1, 'Valle del Cauca'),
(2, 'AGRO-4412', 'Centro Agroempresarial y Acuícola', 3, 'Valle del Cauca'),
(3, 'TECN-1088', 'Centro de Tecnologías de la Información y las Comunicaciones', 2, 'Valle del Cauca'),
(4, 'INNO-7004', 'Centro de Innovación SENA Nodo 4', 5, 'Antioquia')
ON CONFLICT (id) DO NOTHING;

INSERT INTO training_groups (id, number, training_program, schedule, status, training_center_id, created_at) VALUES
(1, '2345678', 'ADSO - Análisis y Desarrollo de Software', 'DIURNA', 'Activo', 1, '2023-01-15 00:00:00+00'),
(2, '2345679', 'ADSO - Análisis y Desarrollo de Software', 'NOCTURNA', 'Activo', 1, '2023-02-10 00:00:00+00'),
(3, '2345680', 'TPSI - Tecnólogo en Producción de Sistemas de Información', 'MIXTA', 'Inactivo', 1, '2022-08-01 00:00:00+00'),
(4, '2451290', 'Tecnología en Producción Agropecuaria Ecológica', 'DIURNA', 'Activo', 1, '2023-03-20 00:00:00+00'),
(5, '2589340', 'Control Ambiental y Sostenibilidad', 'MIXTA', 'Activo', 1, '2023-04-12 00:00:00+00')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, document_type, document, full_name, email, phone, role, status, created_at) VALUES
(1, 'CC', '1023456789', 'Ana Martínez', 'amartinez@sena.edu.co', '+57 300 123 4567', 'ADMINISTRADOR', 'Activo', '2023-01-10 00:00:00+00'),
(2, 'CC', '9876543210', 'Carlos Ramírez', 'cramirez@misena.edu.co', '+57 311 555 7890', 'INSTRUCTOR', 'Activo', '2023-02-14 00:00:00+00'),
(3, 'TI', '1122334455', 'Laura Gómez', 'lgomez@misena.edu.co', '+57 315 444 3322', 'APRENDIZ', 'Inactivo', '2023-03-01 00:00:00+00'),
(4, 'CC', '52345678', 'Dra. María Elena Gómez', 'mgomez@sena.edu.co', '+57 310 987 6543', 'INSTRUCTOR', 'Activo', '2022-11-20 00:00:00+00'),
(5, 'CC', '1005678901', 'Juan Pérez', 'jperez@misena.edu.co', '+57 320 111 2233', 'APRENDIZ', 'Activo', '2023-01-25 00:00:00+00'),
(6, 'CC', '71234567', 'Ing. Carlos Rodríguez', 'crodriguez@sena.edu.co', '+57 301 777 8899', 'INSTRUCTOR', 'Activo', '2023-02-05 00:00:00+00'),
(7, 'CC', '1032456789', 'Ana López', 'alopez@sena.edu.co', '+57 318 333 4455', 'INSTRUCTOR', 'Activo', '2023-01-05 00:00:00+00')
ON CONFLICT (id) DO NOTHING;

INSERT INTO projects (
  id, name, training_center_id, training_center_name, regional_name, beneficiaries, executive_summary,
  keywords, general_objective, specific_objectives, start_date, end_date, total_budget,
  status, progress, created_by_user_id, is_deleted, created_at, updated_at
) VALUES
(1, 'Desarrollo de Bioplásticos a partir de Residuos de Cacao', 2, 'Centro Agroempresarial', 'Valle del Cauca', 'Instructores, aprendices de agroindustria y productores cacaoteros de la región Valle del Cauca.', 'Investigación orientada al aprovechamiento de la cascarilla y mucílago de cacao para la síntesis de biopolímeros biodegradables compostables, reduciendo la huella de carbono en empaques agrícolas.', '["Bioplásticos", "Economía Circular", "Cacao", "Sostenibilidad", "Biopolímeros"]'::jsonb, 'Sintetizar y caracterizar películas biodegradables a partir del almidón y celulosa extraídos de los residuos agroindustriales del cacao.', '["Extraer y purificar celulosa a partir de la cáscara de cacao.", "Formular matrices poliméricas con plastificantes naturales.", "Evaluar la tasa de biodegradabilidad en suelos del centro de formación."]'::jsonb, '2024-02-01', '2024-11-30', 35000000.00, 'EN EJECUCIÓN', 65, 4, false, '2024-01-20 00:00:00+00', '2024-05-15 00:00:00+00'),
(2, 'Sistema IoT para Monitoreo de Calidad del Agua en Acuicultura', 3, 'Centro de Tecnología', 'Valle del Cauca', 'Piscicultores de especies menores y centros acuícolas del SENA.', 'Diseño e implementación de una red de sensores sumergibles con microcontroladores ESP32 para telemetría en tiempo real de pH, oxígeno disuelto y temperatura con alertas tempranas vía LoRaWAN.', '["IoT", "Acuicultura", "Sensores", "Telemetría", "Sistemas Embebidos"]'::jsonb, 'Desarrollar un prototipo de monitoreo continuo multiparamétrico para estanques piscícolas.', '["Diseñar la circuitería electrónica y sondas de calibración.", "Configurar el protocolo de comunicación inalámbrica de bajo consumo.", "Desplegar un panel de control con visualización web y móvil."]'::jsonb, '2023-05-10', '2023-12-15', 28000000.00, 'INACTIVO', 15, 6, false, '2023-05-01 00:00:00+00', '2023-05-01 00:00:00+00'),
(3, 'Implementación de Energías Renovables en Zonas Rurales Aisladas', 4, 'Centro de Innovación', 'Antioquia', 'Comunidades rurales no interconectadas y aprendices de energías limpias.', 'Instalación y evaluación de un microrred fotovoltaica híbrida con almacenamiento en baterías de litio-ferrofosfato para energizar centros comunitarios rurales.', '["Energía Solar", "Fotovoltaica", "Zonas No Interconectadas", "Sostenibilidad"]'::jsonb, 'Evaluar el desempeño técnico y socioeconómico de sistemas fotovoltaicos aislados.', '["Dimensionar la capacidad de generación fotovoltaica según la demanda local.", "Capacitar a líderes comunitarios en mantenimiento preventivo.", "Medir la reducción de emisiones de CO2 frente a generadores diésel."]'::jsonb, '2024-01-15', '2024-10-30', 52000000.00, 'EN EJECUCIÓN', 88, 2, false, '2024-01-10 00:00:00+00', '2024-01-10 00:00:00+00'),
(4, 'Evaluación de Sistemas Acuapónicos en Climas Templados', 1, 'CLEM - Centro Latinoamericano de Especies Menores', 'Valle del Cauca', 'Productores de especies menores y aprendices del CLEM.', 'Integración simbiótica de cultivo hidropónico de hortalizas con producción acuícola de tilapia roja, optimizando la recirculación de nutrientes y el uso eficiente del agua.', '["Acuaponía", "Sostenibilidad", "Tilapia", "Hidroponía", "CLEM"]'::jsonb, 'Evaluar la eficiencia biológica y productiva de un sistema acuapónico de ciclo cerrado en el centro CLEM.', '["Monitorear la tasa de asimilación de nitratos en plantas de lechuga.", "Analizar los costos operativos frente a sistemas agrícolas tradicionales.", "Estandarizar el protocolo de desinfección biológica."]'::jsonb, '2024-03-01', '2024-12-20', 42000000.00, 'ACTIVO', 40, 7, false, '2024-02-28 00:00:00+00', '2024-02-28 00:00:00+00'),
(5, 'Optimización Nutricional en Lombricultura con Subproductos del Café', 1, 'CLEM - Centro Latinoamericano de Especies Menores', 'Valle del Cauca', 'Asociaciones caficultoras y aprendices de biotecnología agropecuaria.', 'Evaluación del crecimiento poblacional y calidad de humus de lombriz roja californiana (Eisenia foetida) alimentada con pulpa de café compostada y rumen bovino.', '["Lombricultura", "Humus", "Café", "Abono Orgánico", "CLEM"]'::jsonb, 'Determinar la tasa óptima de enriquecimiento orgánico en lechos de lombricultura.', '["Caracterizar físico-químicamente el sustrato de pulpa de café precompostada.", "Medir la tasa reproductiva mensual de Eisenia foetida.", "Cuantificar el contenido de N-P-K en el lixiviado y abono sólido producido."]'::jsonb, '2023-08-01', '2024-06-30', 19500000.00, 'ACTIVO', 75, 2, false, '2023-07-25 00:00:00+00', '2023-07-25 00:00:00+00')
ON CONFLICT (id) DO NOTHING;

INSERT INTO project_authors (id, project_id, user_id, is_principal) VALUES
(1, 1, 4, true), (2, 1, 5, false), (3, 2, 6, true), (4, 3, 2, true), (5, 3, 7, false), (6, 4, 7, true), (7, 4, 5, false), (8, 5, 2, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO project_training_groups (id, project_id, training_group_id) VALUES
(1, 1, 4), (2, 2, 1), (3, 3, 5), (4, 4, 4), (5, 5, 4)
ON CONFLICT (id) DO NOTHING;

INSERT INTO activity_logs (id, user_id, user_name, user_avatar, action_label, action_type, detail, module, payload, timestamp) VALUES
(1, 1, 'Ana Martínez', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop', 'Creación de Usuario', 'user_created', 'Se registró el usuario Carlos Pérez con rol Investigador.', 'Usuarios', NULL, '2023-10-27 10:30:00+00'),
(2, 5, 'Carlos Pérez', NULL, 'Actualización Proyecto', 'project_updated', 'Se modificó el estado de "Proyecto Genoma" a En Progreso.', 'Proyectos', NULL, '2023-10-27 09:15:00+00'),
(3, 3, 'Jorge López', NULL, 'Eliminación Registro', 'project_deleted', 'Se eliminó el dataset obsoleto #4092.', 'Proyectos', NULL, '2023-10-26 16:45:00+00'),
(4, 1, 'Ana Martínez', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop', 'Cambio Configuración', 'config_changed', 'Se ajustaron los parámetros de retención de logs a 90 días.', 'Configuración', NULL, '2023-10-26 11:20:00+00')
ON CONFLICT (id) DO NOTHING;

SELECT setval('training_groups_id_seq', (SELECT COALESCE(MAX(id), 1) FROM training_groups));
SELECT setval('users_id_seq', (SELECT COALESCE(MAX(id), 1) FROM users));
SELECT setval('projects_id_seq', (SELECT COALESCE(MAX(id), 1) FROM projects));
SELECT setval('project_authors_id_seq', (SELECT COALESCE(MAX(id), 1) FROM project_authors));
SELECT setval('project_training_groups_id_seq', (SELECT COALESCE(MAX(id), 1) FROM project_training_groups));
SELECT setval('project_attachments_id_seq', (SELECT COALESCE(MAX(id), 1) FROM project_attachments));
SELECT setval('activity_logs_id_seq', (SELECT COALESCE(MAX(id), 1) FROM activity_logs));`;

    if (navigator.clipboard) {
      navigator.clipboard.writeText(sqlText);
      setCopiedSql(true);
      setTimeout(() => setCopiedSql(false), 2500);
    }
  };

  const isAdmin = currentUser?.role === 'ADMINISTRADOR';

  const handleReconnect = async () => {
    if (!onReconnectDb) return;
    setIsReconnecting(true);
    try {
      await onReconnectDb();
    } finally {
      setTimeout(() => setIsReconnecting(false), 600);
    }
  };

  const getRoleBadge = (role: string) => {
    switch (role) {
      case 'ADMINISTRADOR':
        return 'Admin';
      case 'INSTRUCTOR':
        return 'Instructor';
      case 'APRENDIZ':
        return 'Aprendiz';
      default:
        return 'Researcher';
    }
  };

  return (
    <>
      <header className="docked full-width top-0 sticky bg-[#f5fceb]/80 backdrop-blur-xl border-b border-white/30 shadow-[0_4px_12px_0_rgba(0,50,77,0.05)] flex justify-between items-center w-full h-20 px-6 md:px-8 z-30">
        {/* Mobile Menu Button + Title */}
        <div className="flex items-center gap-3 md:hidden">
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="p-2 text-[#171d13] rounded-lg hover:bg-[#e4ebda]"
            aria-label="Abrir menú"
          >
            <span className="material-symbols-outlined">menu</span>
          </button>
          <span className="font-montserrat text-xl font-black text-[#39a900]">DynaPro</span>
        </div>

        {/* Desktop Brand / Breadcrumb */}
        <div className="hidden md:flex items-center gap-3">
          <span
            onClick={() => setActiveView('projects')}
            className="font-montserrat text-2xl font-black text-[#39a900] tracking-tight cursor-pointer"
          >
            DynaPro
          </span>
          <span className="text-[#6f7b66] text-xs font-mono bg-[#eff6e5] px-2 py-0.5 rounded-full border border-[#dee5d4]">
            CLEM v1.0
          </span>

          {/* Supabase Connection Pill (Solo visible para rol ADMINISTRADOR) */}
          {isAdmin && (
            <button
              onClick={() => setShowDbModal(true)}
              className={`flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium border transition-all cursor-pointer ${dbStatus?.connected
                ? 'bg-[#8afd5d]/20 text-[#0c3400] border-[#39a900]/40 hover:bg-[#8afd5d]/30'
                : 'bg-[#e0f2fe] text-[#0369a1] border-[#bae6fd] hover:bg-[#bae6fd]/50'
                }`}
              title="Ver estado de conexión con la base de datos Supabase"
            >
              <span
                className={`w-2 h-2 rounded-full ${dbStatus?.connected ? 'bg-[#39a900] animate-pulse' : 'bg-[#0284c7]'
                  }`}
              />
              <span className="font-bold">
                {dbStatus?.connected ? 'Supabase Conectado' : 'Supabase (Modo Seguro)'}
              </span>
              {dbStatus?.latencyMs ? (
                <span className="text-[10px] opacity-75 font-mono">({dbStatus.latencyMs}ms)</span>
              ) : null}
            </button>
          )}
        </div>

        {/* Right Action Icons & User Profile */}
        <div className="flex items-center gap-4">
          {/* Quick RBAC Switcher Dropdown (Helpful for test evaluators!) */}
          <div className="relative">
            <button
              onClick={() => setShowUserMenu(!showUserMenu)}
              className="flex items-center gap-2.5 bg-[#eff6e5] hover:bg-[#e4ebda] border border-white/40 shadow-sm py-1.5 px-3 rounded-full transition-all cursor-pointer group"
              title="Cambiar rol o usuario para probar RBAC"
            >
              <div className="w-8 h-8 rounded-full overflow-hidden border border-[#39a900]/40 bg-[#39a900]/20 flex items-center justify-center shrink-0">
                <span className="text-xs font-bold text-[#226d00]">
                  {currentUser?.full_name?.slice(0, 2).toUpperCase() || 'US'}
                </span>
              </div>
              <div className="hidden sm:flex flex-col text-left">
                <span className="text-xs font-semibold text-[#171d13] leading-tight">
                  {currentUser?.full_name || 'Invitado'}
                </span>
                <span className="text-[11px] text-[#226d00] font-medium leading-tight">
                  {currentUser ? getRoleBadge(currentUser.role) : 'Sin sesión'}
                </span>
              </div>
              <span className="material-symbols-outlined text-[18px] text-[#6f7b66] group-hover:text-[#171d13]">
                expand_more
              </span>
            </button>

            {/* Switch User Dropdown */}
            {showUserMenu && (
              <div className="absolute right-0 mt-2 w-72 bg-white/95 backdrop-blur-xl rounded-2xl shadow-2xl border border-white/60 p-3 z-50 animate-in fade-in slide-in-from-top-2 duration-150">
                <div className="px-3 py-2 border-b border-[#dee5d4] mb-2">
                  <p className="text-sm font-bold text-[#171d13] mt-0.5">{currentUser?.full_name}</p>
                  <p className="text-xs text-[#3c627f]">{currentUser?.email}</p>
                  <span className="inline-block mt-1.5 px-2 py-0.5 rounded-full text-[11px] font-bold bg-[#8afd5d]/30 text-[#0c3400]">
                    {currentUser?.role}
                  </span>
                </div>

                <div className="flex flex-col gap-1 pt-1">
                  <button
                    onClick={() => {
                      setShowUserMenu(false);
                      setActiveView('profile');
                    }}
                    className="text-xs text-left px-3 py-1.5 rounded-lg text-[#3f4a38] hover:bg-[#eff6e5] flex items-center gap-2 font-medium cursor-pointer"
                  >
                    <span className="material-symbols-outlined text-[16px] text-[#39a900]">account_circle</span>
                    Mi Perfil
                  </button>
                  <button
                    onClick={() => {
                      setShowUserMenu(false);
                      setShowChangePasswordModal(true);
                    }}
                    className="text-xs text-left px-3 py-1.5 rounded-lg text-[#3f4a38] hover:bg-[#eff6e5] flex items-center gap-2 font-medium cursor-pointer transition-colors"
                  >
                    <span className="material-symbols-outlined text-[16px] text-[#39a900]">lock_reset</span>
                    Cambiar Contraseña
                  </button>
                  <button
                    onClick={() => {
                      setShowUserMenu(false);
                      setActiveView('about');
                    }}
                    className="text-xs text-left px-3 py-1.5 rounded-lg text-[#3f4a38] hover:bg-[#eff6e5] cursor-pointer"
                  >
                    Acerca de DynaPro
                  </button>
                  <button
                    onClick={() => {
                      setShowUserMenu(false);
                      onLogout();
                    }}
                    className="text-xs text-left px-3 py-1.5 rounded-lg text-[#ba1a1a] hover:bg-[#ffdad6] font-medium"
                  >
                    Cerrar sesión
                  </button>
                </div>
              </div>
            )}
          </div>

        </div>
      </header>

      {/* Supabase Connection Status Modal (Solo visible para rol ADMINISTRADOR) */}
      {showDbModal && isAdmin && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="fixed inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setShowDbModal(false)} />
          <div className="relative bg-white rounded-3xl max-w-lg w-full p-6 md:p-8 shadow-2xl z-10 border border-white/60 space-y-5 max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-start pb-4 border-b border-[#dee5d4]">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[#3ecf8e]/10 border border-[#3ecf8e]/30 flex items-center justify-center text-[#24b47e]">
                  <span className="material-symbols-outlined text-2xl">
                    cloud_done
                  </span>
                </div>
                <div>
                  <h3 className="font-montserrat font-bold text-lg text-[#171d13] flex items-center gap-2">
                    Supabase Cloud Database
                    <span className="text-[10px] bg-[#eff6e5] text-[#226d00] font-mono px-2 py-0.5 rounded-full border border-[#dee5d4]">
                      PostgreSQL
                    </span>
                  </h3>
                  <p className="text-xs text-[#6f7b66]">
                    Repositorio persistente en la nube para DynaPro - SENA CLEM
                  </p>
                </div>
              </div>
              <button onClick={() => setShowDbModal(false)} className="p-1 rounded-lg hover:bg-[#eff6e5] cursor-pointer">
                <span className="material-symbols-outlined">close</span>
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div className="flex justify-between items-center p-3 bg-[#eff6e5] rounded-xl">
                <span className="font-semibold text-[#3f4a38]">Estado del Backend:</span>
                <span
                  className={`px-3 py-1 rounded-full font-bold flex items-center gap-1.5 ${dbStatus?.connected
                    ? 'bg-[#8afd5d]/30 text-[#0c3400]'
                    : 'bg-[#e0f2fe] text-[#0369a1]'
                    }`}
                >
                  <span
                    className={`w-2 h-2 rounded-full ${dbStatus?.connected ? 'bg-[#39a900] animate-pulse' : 'bg-[#0284c7]'
                      }`}
                  />
                  {dbStatus?.connected ? 'Conectado a Supabase' : 'Modo Seguro (Memoria Activa)'}
                </span>
              </div>

              <div className="p-3 bg-[#f7f9fb] rounded-xl border border-[#dee5d4] space-y-1">
                <span className="font-semibold text-[#6f7b66] block">Endpoint Supabase:</span>
                <span className="font-mono font-bold text-[#171d13] break-all block">
                  {dbStatus?.supabaseUrl || 'Configurado vía SUPABASE_URL en variables de entorno'}
                </span>
              </div>

              {dbStatus?.tablesCount && (
                <div className="p-3 bg-[#eff6e5] rounded-xl border border-[#dee5d4]/60 space-y-2">
                  <div className="flex justify-between items-center">
                    <span className="font-bold text-[#171d13] block">
                      Tablas Sincronizadas en Tiempo Real:
                    </span>
                    {dbStatus?.latencyMs ? (
                      <span className="text-[10px] text-[#226d00] font-mono font-bold">
                        Latencia: {dbStatus.latencyMs}ms
                      </span>
                    ) : null}
                  </div>
                  <div className="grid grid-cols-3 gap-2 font-mono text-[11px]">
                    <div className="bg-white p-2 rounded-lg text-center shadow-xs border border-[#dee5d4]">
                      <span className="text-[#6f7b66] block text-[10px]">projects</span>
                      <strong className="text-sm text-[#226d00]">{dbStatus.tablesCount.projects}</strong>
                    </div>
                    <div className="bg-white p-2 rounded-lg text-center shadow-xs border border-[#dee5d4]">
                      <span className="text-[#6f7b66] block text-[10px]">users</span>
                      <strong className="text-sm text-[#3c627f]">{dbStatus.tablesCount.users}</strong>
                    </div>
                    <div className="bg-white p-2 rounded-lg text-center shadow-xs border border-[#dee5d4]">
                      <span className="text-[#6f7b66] block text-[10px]">training_groups</span>
                      <strong className="text-sm text-[#171d13]">{dbStatus.tablesCount.training_groups}</strong>
                    </div>
                    <div className="bg-white p-2 rounded-lg text-center shadow-xs border border-[#dee5d4]">
                      <span className="text-[#6f7b66] block text-[10px]">training_centers</span>
                      <strong className="text-sm text-[#171d13]">{dbStatus.tablesCount.training_centers}</strong>
                    </div>
                    <div className="bg-white p-2 rounded-lg text-center shadow-xs border border-[#dee5d4] col-span-2">
                      <span className="text-[#6f7b66] block text-[10px]">activity_logs (Auditoría)</span>
                      <strong className="text-sm text-[#171d13]">{dbStatus.tablesCount.activity_logs}</strong>
                    </div>
                  </div>
                </div>
              )}

              {/* Supabase Quick Setup Card */}
              <div className="p-3.5 bg-[#f0fdf4] rounded-xl border border-[#bbf7d0] text-[#166534] space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-bold flex items-center gap-1.5 text-xs text-[#14532d]">
                    <span className="material-symbols-outlined text-[16px] text-[#22c55e]">terminal</span>
                    Esquema SQL para Supabase (1-Clic)
                  </span>
                  <button
                    onClick={handleCopySql}
                    className="flex items-center gap-1 px-2.5 py-1 bg-white hover:bg-[#dcfce7] border border-[#86efac] text-[#15803d] rounded-lg font-bold text-[11px] transition-all cursor-pointer shadow-xs"
                  >
                    <span className="material-symbols-outlined text-[14px]">
                      {copiedSql ? 'check' : 'content_copy'}
                    </span>
                    {copiedSql ? '¡Copiado!' : 'Copiar SQL'}
                  </button>
                </div>
                <p className="text-[11px] text-[#166534]/90 leading-relaxed">
                  Para inicializar la base de datos en Supabase, abre el <strong>SQL Editor</strong> en tu panel de Supabase, pega el script copiado y haz clic en <strong>RUN</strong>. Luego ingresa tu <code>SUPABASE_URL</code> y <code>SUPABASE_ANON_KEY</code>.
                </p>
              </div>

              {dbStatus?.error && (
                <div className="p-3 bg-[#fef3c7]/60 rounded-xl border border-[#fde68a] text-[#92400e]">
                  <span className="font-bold block mb-1 flex items-center gap-1.5 text-xs">
                    <span className="material-symbols-outlined text-[16px]">info</span>
                    Información de Estado:
                  </span>
                  <p className="font-mono text-[11px] leading-relaxed break-all">{dbStatus.error}</p>
                </div>
              )}
            </div>

            <div className="flex justify-between items-center pt-3 border-t border-[#dee5d4]">
              <button
                type="button"
                onClick={handleReconnect}
                disabled={isReconnecting}
                className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-[#eff6e5] text-[#226d00] hover:bg-[#dee5d4] font-bold text-xs transition-colors cursor-pointer"
              >
                <span className={`material-symbols-outlined text-[16px] ${isReconnecting ? 'animate-spin' : ''}`}>
                  refresh
                </span>
                {isReconnecting ? 'Verificando...' : 'Reconectar / Probar'}
              </button>

              <button
                type="button"
                onClick={() => setShowDbModal(false)}
                className="px-6 py-2 rounded-xl bg-[#39a900] text-white font-montserrat font-bold text-xs hover:bg-[#226d00] transition-colors cursor-pointer"
              >
                Cerrar
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Mobile Drawer Navigation */}
      {mobileMenuOpen && (
        <div className="fixed inset-0 z-50 md:hidden flex">
          <div
            className="fixed inset-0 bg-black/40 backdrop-blur-sm"
            onClick={() => setMobileMenuOpen(false)}
          />
          <div className="relative w-72 bg-white h-full shadow-2xl p-6 flex flex-col z-10">
            <div className="flex justify-between items-center mb-8">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-full bg-[#226d00] flex items-center justify-center">
                  <img
                    src="https://upload.wikimedia.org/wikipedia/commons/8/83/Sena_Colombia_logo.svg"
                    alt="SENA Logo"
                    className="w-5 h-5 invert brightness-0"
                  />
                </div>
                <span className="font-montserrat text-xl font-bold text-[#39a900]">DynaPro</span>
              </div>
              <button
                onClick={() => setMobileMenuOpen(false)}
                className="p-1 rounded-lg hover:bg-gray-100"
              >
                <span className="material-symbols-outlined">close</span>
              </button>
            </div>

            <nav className="flex-1 space-y-2">
              <button
                onClick={() => {
                  setActiveView('dashboard');
                  setMobileMenuOpen(false);
                }}
                className={`flex items-center gap-3 w-full p-3 rounded-xl text-left font-medium ${activeView === 'dashboard' ? 'bg-[#8afd5d]/20 text-[#226d00] font-bold' : 'text-[#3f4a38]'
                  }`}
              >
                <span className="material-symbols-outlined">dashboard</span>
                Tablero
              </button>
              <button
                onClick={() => {
                  setActiveView('projects');
                  setMobileMenuOpen(false);
                }}
                className={`flex items-center gap-3 w-full p-3 rounded-xl text-left font-medium ${activeView === 'projects' || activeView === 'new-project'
                  ? 'bg-[#8afd5d]/20 text-[#226d00] font-bold'
                  : 'text-[#3f4a38]'
                  }`}
              >
                <span className="material-symbols-outlined">science</span>
                Proyectos
              </button>
              {isAdmin && (
                <button
                  onClick={() => {
                    setActiveView('users');
                    setMobileMenuOpen(false);
                  }}
                  className={`flex items-center gap-3 w-full p-3 rounded-xl text-left font-medium ${activeView === 'users' ? 'bg-[#8afd5d]/20 text-[#226d00] font-bold' : 'text-[#3f4a38]'
                    }`}
                >
                  <span className="material-symbols-outlined">group</span>
                  Usuarios
                </button>
              )}
              <button
                onClick={() => {
                  setActiveView('groups');
                  setMobileMenuOpen(false);
                }}
                className={`flex items-center gap-3 w-full p-3 rounded-xl text-left font-medium ${activeView === 'groups' ? 'bg-[#8afd5d]/20 text-[#226d00] font-bold' : 'text-[#3f4a38]'
                  }`}
              >
                <span className="material-symbols-outlined">school</span>
                Grupos de Formación
              </button>
              {isAdmin && (
                <>
                  <button
                    onClick={() => {
                      setActiveView('centers');
                      setMobileMenuOpen(false);
                    }}
                    className={`flex items-center gap-3 w-full p-3 rounded-xl text-left font-medium ${activeView === 'centers' ? 'bg-[#8afd5d]/20 text-[#226d00] font-bold' : 'text-[#3f4a38]'
                      }`}
                  >
                    <span className="material-symbols-outlined">apartment</span>
                    Centros de Formación
                  </button>
                  <button
                    onClick={() => {
                      setActiveView('activity-log');
                      setMobileMenuOpen(false);
                    }}
                    className={`flex items-center gap-3 w-full p-3 rounded-xl text-left font-medium ${activeView === 'activity-log' ? 'bg-[#8afd5d]/20 text-[#226d00] font-bold' : 'text-[#3f4a38]'
                      }`}
                  >
                    <span className="material-symbols-outlined">history</span>
                    Log de Actividades
                  </button>
                </>
              )}
              <button
                onClick={() => {
                  setActiveView('profile');
                  setMobileMenuOpen(false);
                }}
                className={`flex items-center gap-3 w-full p-3 rounded-xl text-left font-medium ${activeView === 'profile' ? 'bg-[#8afd5d]/20 text-[#226d00] font-bold' : 'text-[#3f4a38]'
                  }`}
              >
                <span className="material-symbols-outlined">account_circle</span>
                Mi Perfil
              </button>
              <button
                onClick={() => {
                  setMobileMenuOpen(false);
                  setShowChangePasswordModal(true);
                }}
                className="flex items-center gap-3 w-full p-3 rounded-xl text-left font-medium text-[#3f4a38] hover:bg-[#eff6e5] transition-colors"
              >
                <span className="material-symbols-outlined text-[#39a900]">lock_reset</span>
                Cambiar Contraseña
              </button>
            </nav>

            <div className="pt-4 border-t border-gray-100">
              <button
                onClick={() => {
                  setMobileMenuOpen(false);
                  onLogout();
                }}
                className="flex items-center gap-3 w-full p-3 text-red-600 font-medium"
              >
                <span className="material-symbols-outlined">logout</span>
                Cerrar sesión
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Change Password Modal */}
      <ChangePasswordModal
        isOpen={showChangePasswordModal}
        onClose={() => setShowChangePasswordModal(false)}
        currentUser={currentUser}
        onToast={onToast}
      />
    </>
  );
};
